BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
            text: ''
            multiline: False

        Button:
            text: 'Square'
            on_press: app.handle_calculate()

        Label:
            id: output_label
            text: ''
            color: (1, 0.6, 0.8, 1)

    Label:
        text: 'Enter a number and press "Square"'